<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Authentication_model extends CI_Model {

    public $table = 'users';
    public $id = 'id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // insert data
    function checklogin($username, $password) {
        $this->db->where("username", $username);
        $this->db->where("password", $password);
        $this->db->where("isactive", 1);
        return $this->db->get($this->table)->row();
    }

    //lock or unlock user after login/logout
    public function loginstat($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-06-21 12:45:37 */
/* http://harviacode.com */