<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Icons_model extends CI_Model {

    public $table = 'icons';
    public $id = 'icon';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

}

/* End of file Roles_model.php */
/* Location: ./application/models/Roles_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2020-09-14 19:52:53 */
/* http://harviacode.com */