<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Users_model extends CI_Model {

    public $table = 'users';
    public $id = 'id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    //get user with full profile
    function get_all_with_profile() {
        $this->db->select('u.*,ud.fullname');
        $this->db->from('users u');
        $this->db->join('userdetails ud', 'ud.userid=u.id', 'left');
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    //get data by email
    function get_by_email($email) {
        $this->db->select('u.*,ud.fullname');
        $this->db->from('users u');
        $this->db->join('userdetails ud', 'ud.userid=u.id', 'left');
        $this->db->where('u.email', $email);
        return $this->db->get()->row();
    }

    // get data by username & email
    function get_by_username_email($user, $email) {
        $this->db->where('username', $user);
        $this->db->where('email', $email);
        return $this->db->get($this->table)->row();
    }

    // get data by username & password
    function get_by_username_password($user, $password) {
        $this->db->where('username', $user);
        $this->db->where('password', $password);
        return $this->db->get($this->table)->row();
    }

    //generate resetkey
    function generate_resetkey($email) {
        $this->db->where('email', $email);
        $this->db->update($this->table, array('resetkey' => $this->uuid->v3($email, '')));
    }

    function get_by_resetkey($resetkey) {
        $this->db->where('resetkey', $resetkey);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('username', $q);
        $this->db->or_like('email', $q);
        $this->db->or_like('password', $q);
        $this->db->or_like('status', $q);
        $this->db->or_like('role', $q);
        $this->db->or_like('resetkey', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->select('u.*,r.rolename');
        $this->db->from('users u');
        $this->db->join('roles r', 'r.id=u.role', 'left');
        $this->db->group_start();
        $this->db->like('u.id', $q);
        $this->db->or_like('u.username', $q);
        $this->db->or_like('u.email', $q);
        $this->db->or_like('u.password', $q);
        $this->db->or_like('u.status', $q);
        $this->db->or_like('u.role', $q);
        $this->db->or_like('u.resetkey', $q);
        $this->db->or_like('u.createdat', $q);
        $this->db->or_like('u.createdby', $q);
        $this->db->or_like('u.updatedat', $q);
        $this->db->or_like('u.updatedby', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Users_model.php */
/* Location: ./application/models/Users_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-01-04 06:40:06 */
/* http://harviacode.com */