<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Categories_model extends CI_Model {

    public $table = 'categories';
    public $id = 'id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    function get_enrolledto($roleid) {
        $this->db->distinct();
        $this->db->where('enrolledto', $roleid);
        return $this->db->get($this->table)->row();
    }

    // get all with enrolled status
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get data by slug
    function get_by_slug($slug) {
        $this->db->where("slug", $slug);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($where, $q = NULL) {
        $this->db->from($this->table);
        $this->db->where($where);
        $this->db->group_start();
        $this->db->like('categories.id', $q);
        $this->db->or_like('categories.category', $q);
        $this->db->or_like('categories.slug', $q);
        $this->db->or_like('categories.createdat', $q);
        $this->db->or_like('categories.createdby', $q);
        $this->db->or_like('categories.updatedat', $q);
        $this->db->or_like('categories.updatedby', $q);
        $this->db->group_end();
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($where, $limit, $start = 0, $q = NULL) {
        $this->db->select('categories.*');
        $this->db->from($this->table);
        $this->db->where($where);
        $this->db->order_by('categories.id', $this->order);
        $this->db->group_start();
        $this->db->like('categories.id', $q);
        $this->db->or_like('categories.category', $q);
        $this->db->or_like('categories.slug', $q);
        $this->db->or_like('categories.createdat', $q);
        $this->db->or_like('categories.createdby', $q);
        $this->db->or_like('categories.updatedat', $q);
        $this->db->or_like('categories.updatedby', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Categories_model.php */
/* Location: ./application/models/Categories_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-11-07 12:59:55 */
/* http://harviacode.com */