<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Documentcategories_model extends CI_Model {

    public $table = 'documentcategories';
    public $id = 'id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all() {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id) {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    function get_by_slug($slug) {
        $this->db->where('slug', $slug);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id', $q);
        $this->db->or_like('category', $q);
        $this->db->or_like('slug', $q);
        $this->db->or_like('acronym', $q);
        $this->db->or_like('acslug', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('category', $q);
        $this->db->or_like('slug', $q);
        $this->db->or_like('acronym', $q);
        $this->db->or_like('acslug', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Documentcategories_model.php */
/* Location: ./application/models/Documentcategories_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2023-11-02 14:43:59 */
/* http://harviacode.com */