<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Externallinks_model extends CI_Model {

    public $table = 'posts';
    public $id = 'id';
    public $order = 'ASC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all($type = 'link') {
        $this->db->where('type', $type);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id, $type = 'link') {
        $this->db->where('type', $type);
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL, $type = 'link') {
        $this->db->from($this->table);
        $this->db->where('type', $type);
        $this->db->group_start();
        $this->db->like('posts.id', $q);
        $this->db->or_like('posts.title', $q);
        $this->db->or_like('posts.content', $q);
        $this->db->or_like('posts.createdat', $q);
        $this->db->or_like('posts.createdby', $q);
        $this->db->or_like('posts.updatedat', $q);
        $this->db->or_like('posts.updatedby', $q);
        $this->db->group_end();
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $type = 'link') {
        $this->db->select('posts.*');
        $this->db->from($this->table);
        $this->db->where('type', $type);
        $this->db->order_by('posts.id', $this->order);
        $this->db->group_start();
        $this->db->like('posts.id', $q);
        $this->db->or_like('posts.title', $q);
        $this->db->or_like('posts.content', $q);
        $this->db->or_like('posts.createdat', $q);
        $this->db->or_like('posts.createdby', $q);
        $this->db->or_like('posts.updatedat', $q);
        $this->db->or_like('posts.updatedby', $q);
        $this->db->group_end();
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Categories_model.php */
/* Location: ./application/models/Categories_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-11-07 12:59:55 */
/* http://harviacode.com */