<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Media_model extends CI_Model
{

    public $table = 'media';
    public $id = 'id';
    public $order = 'ASC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    // get all count
    function get_all_count()
    {
        return $this->db->count_all($this->table);
    }

    function get_all_by_type($type)
    {
        $this->db->like('filetype', $type);
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL)
    {
        $this->db->like('id', $q);
        $this->db->or_like('filename', $q);
        $this->db->or_like('filepath', $q);
        $this->db->or_like('fullpath', $q);
        $this->db->or_like('filetype', $q);
        $this->db->or_like('descriptions', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL)
    {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id', $q);
        $this->db->or_like('filename', $q);
        $this->db->or_like('filepath', $q);
        $this->db->or_like('fullpath', $q);
        $this->db->or_like('filetype', $q);
        $this->db->or_like('descriptions', $q);
        $this->db->or_like('createdby', $q);
        $this->db->or_like('createdat', $q);
        $this->db->or_like('updatedby', $q);
        $this->db->or_like('updatedat', $q);
        $this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Media_model.php */
/* Location: ./application/models/Media_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-11-07 12:59:55 */
/* http://harviacode.com */