<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Pages_model extends CI_Model {

    public $table = 'posts';
    public $id = 'id';
    public $order = 'DESC';

    function __construct() {
        parent::__construct();
    }

    // get all
    function get_all($status = array('poststatus !=' => 4)) {
        $this->db->select('posts.*');
        $this->db->from('posts');
        $this->db->where('posts.type', 'page');
        $this->db->where($status);
        $this->db->order_by('posts.id', $this->order);
        return $this->db->get()->result();
    }

    // get data by id
    function get_by_id($id, $status = array('poststatus !=' => 4)) {
        $this->db->select('posts.*');
        $this->db->from('posts');
        $this->db->where('posts.type', 'page');
        $this->db->where('posts.id', $id);
        $this->db->where($status);
        return $this->db->get()->row();
    }

    // get data by slug
    function get_by_slug($slug, $status = array('posts.poststatus !=' => 4)) {
        $this->db->select('posts.*, users.username, userdetails.fullname');
        $this->db->from('posts');
        $this->db->join('users', 'users.id=posts.createdby', 'left');
        $this->db->join('userdetails', 'userdetails.userid=users.id', 'left');
        $this->db->join('categories', 'categories.id = posts.category', 'left');
        $this->db->where('posts.type', 'page');
        $this->db->where('posts.slug', $slug);
        $this->db->where($status);
        return $this->db->get()->row();
    }

    // get total rows
    function total_rows($q = NULL, $status = array('posts.poststatus !=' => 4)) {
        $this->db->select('posts.*, categories.category as categoryname');
        $this->db->join('categories', 'categories.id = posts.category', 'left');
        $this->db->where('posts.type', 'page');
        $this->db->where($status);
        $this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL, $status = array('posts.poststatus != ' => 4)) {
        $this->db->select('posts.*, categories.category as categoryname,roles.rolename');
        $this->db->join('categories', 'categories.id = posts.category', 'left');
        $this->db->join('roles', 'roles.id=posts.enrolledto', 'left');
        $this->db->from('posts');
        $this->db->where('posts.type', 'page');
        $this->db->where($status);
        $this->db->order_by('posts.id', $this->order);
        $this->db->limit($limit, $start);
        return $this->db->get()->result();
    }

    // insert data
    function insert($data) {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data) {
        $this->db->where('type', 'page');
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id) {
        $this->db->where('type ', 'page');
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Posts_model.php */
/* Location: ./application/models/Posts_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-11-07 12:59:55 */
/* http://harviacode.com */