<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Settings extends MY_Controller
{

    function __construct()
    {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->load->model('Settings_model');
        $this->load->model('Auth/Users_model');
        $this->load->library('form_validation');
        $this->sess = $this->session->logged_in;
    }

    public function index()
    {
        $settings = $this->Settings_model->get_all();
        $users = $this->Users_model->get_all_with_profile();
        $data = array(
            'users' => $users,
            'button' => 'Simpan',
            'action' => site_url('app/settings/update_action'),
            'template' => 'settings/settings_form',
            'extrajs' => 'settings/settings_form_extrajs',
            'session' => $this->sess,
        );
        foreach ($settings as $key) {
            $data[$key->setting_name] = $key->setting_value;
        }
        $this->load->view('base/content', $data);
    }

    public function update_action()
    {
        $sttg = $this->input->post();
        $sttg['site_greeting1'] = str_replace("[removed]", "", $this->input->post('site_greeting1', FALSE));
        $sttg['site_greeting2'] = str_replace("[removed]", "", $this->input->post('site_greeting2', FALSE));
        $sttg['smtp_pass'] = base64_encode($sttg['smtp_pass']);
        foreach ($sttg as $key => $val) {
            $this->Settings_model->update($key, array('setting_value' => $val));
        }

        if (!empty($_FILES['filelogo1']['name'])) {
            $result = fileuploader($_FILES, "filelogo1");
            $this->Settings_model->update("site_logo1", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['filehero']['name'])) {
            $result = fileuploader($_FILES, "filehero");
            $this->Settings_model->update("site_hero", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['filelogo2']['name'])) {
            $result = fileuploader($_FILES, "filelogo2");
            $this->Settings_model->update("site_logo2", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['filelogomobile']['name'])) {
            $result = fileuploader($_FILES, "filelogomobile");
            $this->Settings_model->update("site_logo_mobile", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['filefavicon']['name'])) {
            $result = fileuploader($_FILES, "filefavicon");
            $this->Settings_model->update("site_icon", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['site_greeting_pic1']['name'])) {
            $result = fileuploader($_FILES, "site_greeting_pic1");
            $this->Settings_model->update("site_greeting_pic1", array('setting_value' => $result['message']['fullpath']));
        }
        if (!empty($_FILES['site_greeting_pic2']['name'])) {
            $result = fileuploader($_FILES, "site_greeting_pic2");
            $this->Settings_model->update("site_greeting_pic2", array('setting_value' => $result['message']['fullpath']));
        }

        redirect(site_url('app/settings'));
    }

    function _rules($field)
    {
        $this->form_validation->set_rules($field, $field, 'trim|xss_clean');
    }

}

/* End of file Settings.php */
/* Location: ./application/controllers/Settings.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2021-05-17 14:03:47 */
/* http://harviacode.com */