<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

class Surveys extends MY_Controller
{

    public $ifroled, $where;

    function __construct()
    {
        parent::__construct();
        parent::_auth($this->uri->uri_string());
        $this->sess = $this->session->logged_in;
        $this->rolelist = $this->sess['rolelist'][ucfirst($this->uri->segment(2))];
        $this->load->model('Surveys_model');
    }

    public function index()
    {
        $raw = $this->Surveys_model->get_all_count();

        // Normalisasi agar nilai tetap aman meskipun null
        $count_1 = isset($raw->count_1) ? (int) $raw->count_1 : 0;
        $count_2 = isset($raw->count_2) ? (int) $raw->count_2 : 0;
        $count_3 = isset($raw->count_3) ? (int) $raw->count_3 : 0;
        $count_4 = isset($raw->count_4) ? (int) $raw->count_4 : 0;

        // Re-mapping
        $data = array(
            'surveycount' => (object) [
                'suka' => $count_1 + $count_2,
                'tidakSuka' => $count_3 + $count_4,
            ],
            'survey' => $this->Surveys_model->get_all(),
            'svaluetext' => [
                1 => 'Suka',
                2 => 'Suka',
                3 => 'Tidak Suka',
                4 => 'Tidak Suka',
            ],
            'session' => $this->sess,
            'rolelist' => $this->rolelist,
            'template' => 'surveys/surveys_list',
            'extrajs' => 'surveys/surveys_extrajs',
        );

        $this->load->view('base/content', $data);
    }



    public function export_surveys()
    {
        $this->load->model('Surveys_model');
        $survey = $this->Surveys_model->get_all();

        $svaluetext = [
            1 => 'Suka',
            2 => 'Suka',
            3 => 'Tidak Suka',
            4 => 'Tidak Suka',
        ];

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();

        // Set header kolom
        $sheet->setCellValue('A1', 'No');
        $sheet->setCellValue('B1', 'IP Address');
        $sheet->setCellValue('C1', 'Nilai');

        // Isi data
        $row = 2;
        $no = 1;
        foreach ($survey as $s) {
            $sheet->setCellValue('A' . $row, $no++);
            $sheet->setCellValue('B' . $row, $s->ipaddress);
            $sheet->setCellValue('C' . $row, $svaluetext[$s->svalue] ?? '-');
            $row++;
        }

        // Siapkan untuk download
        $filename = 'data_survey_' . date('Ymd_His') . '.xlsx';
        header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
        header("Content-Disposition: attachment;filename=\"$filename\"");
        header('Cache-Control: max-age=0');

        $writer = new Xlsx($spreadsheet);
        $writer->save('php://output');
        exit;
    }

}

/* End of file Categories.php */
/* Location: ./application/controllers/Categories.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2022-11-07 12:59:55 */
/* http://harviacode.com */